export const ANALYZE_LOAD = 'ANALYZE_LOAD';
export const FORTALEZA_SET = 'FORTALEZA_SET';
export const FORTALEZA_DELETE = 'FORTALEZA_DELETE';
export const FORTALEZA_UPDATE = 'FORTALEZA_UPDATE';

export const DEBILIDAD_SET = 'DEBILIDAD_SET';
export const DEBILIDAD_DELETE = 'DEBILIDAD_DELETE';
export const DEBILIDAD_UPDATE = 'DEBILIDAD_UPDATE';

export const OPORTUNIDAD_SET = 'OPORTUNIDAD_SET';
export const OPORTUNIDAD_DELETE = 'OPORTUNIDAD_DELETE';
export const OPORTUNIDAD_UPDATE = 'OPORTUNIDAD_UPDATE';

export const AMENAZA_SET = 'AMENAZA_SET';
export const AMENAZA_DELETE = 'AMENAZA_DELETE';
export const AMENAZA_UPDATE = 'AMENAZA_UPDATE';
